The ``100-matrix_mul`` module
=======================

Using ``matrix_mul``
---------------------

This is a 100-matrix_mul text file to test the matrix_mul function, First
import ``matrix_mul`` from the ``100-matrix_mul`` module:

    >>> matrix_mul = __import__("100-matrix_mul").matrix_mul

Test for module documentation:
    >>> len(__import__("100-matrix_mul").__doc__) > 10
    True

Test for function documentation:
    >>> len(__import__("100-matrix_mul").matrix_mul.__doc__) > 10
    True

Test for normal operation:
         >>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
         [[7, 10], [15, 22]]

Test for few arguments:
	 >>> matrix_mul([[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 TypeError: matrix_mul() missing 1 required positional argument: 'm_b'

Test for extra arguments:
	 >>> matrix_mul([[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]])
	 Traceback (most recent call last):
	 ...
	 TypeError: matrix_mul() takes 2 positional arguments but 3 were given

Test for non list argument:
	 >>> matrix_mul(None, [[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 TypeError: m_a must be a list

Test for non list argument 2:
	 >>> matrix_mul([[1, 2], [3, 4]], None)
	 Traceback (most recent call last):
	 ...
	 TypeError: m_b must be a list

Test for empty list:
	 >>> matrix_mul([], [[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 ValueError: m_a can't be empty

Test for empty rows:
	 >>> matrix_mul([[], []], [[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 ValueError: m_a can't be empty

Test for different size rows:
	 >>> matrix_mul([[1, 2], [3, 4, 5]], [[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 TypeError: each row of m_a must should be of the same size

Test for non number list:
	 >>> matrix_mul([[1, "Hello"], [3, 4]], [[1, 2], [3, 4]])
	 Traceback (most recent call last):
	 ...
	 TypeError: m_a should contain only integers or floats

Test for incompatible arguments:
	 >>> matrix_mul([[1, 2, 3], [4, 5, 6]], [[1, 2], [3, 4,]])
	 Traceback (most recent call last):
	 ...
	 ValueError: m_a and m_b can't be multiplied

